pipeline{
	agent any
	stages{
		stage('Checkout'){
			steps{
				 git branch: "main", url: 'https://github.com/jasdhiratrevature/TRNG-00001988.git'
			}
		}
		stage('Build'){
			steps{
				cd 092624/hello-there
				 sh 'chmod a+x mvnw'
      			  sh './mvnw clean package -DskipTests=true'
			}
		}
	}
}