pipeline{
	agent any
	stages{
		stage('Checkout'){
			steps{
				 git branch: "main", url: 'https://github.com/jasdhiratrevature/TRNG-00001988.git'
			}
		}
		stage('Build'){
			steps{
				echo ' hi'	
				cd '092624/hello-there'
			}
		}
	}
}