pipeline{
	agent any
	stages{
		stage('Checkout'){
			steps{
				 git branch: "main", url: 'https://github.com/jasdhiratrevature/TRNG-00001988.git'
			}
		}
		stage('Build'){
			steps{
				echo ' hi'	
				dir('092624/hello-there'){
					echo 'inside dir'
					bat 'dir'
					// sh 'chmod a+x mvnw'
					bat './mvnw clean package -DskipTests=true'
				}
			}
			 {
        always {
          archiveArtifacts 'target/*.jar'
        }
          }
		}
		stage('DockerBuild') {
      steps {
		bat 'dir'
        //bat 'docker build -t jasdhirtech/hello-there:latest .'
      }
        }
	}
}